### ISSUE TITLE
Change license should be a red button

### ISSUE THREAD

**Issue by mattl** [creativecommons/mp#11]

**Comment by robmyers** [comment]
It's default style to make it less emphasized, as we don't want people being drawn to it a la Stimpy in "Space Madness". We also shouldn't use just colour for emphasis for obvious reasons.

If you'd really like this change, please enter your GPG private key for confirmation.

Also - should we have some text warning people about irrevocability or is that the sort of thing we need to review with others?

**Comment by robmyers** [comment]
Changed.
