### ISSUE TITLE
Implement "Copy Attribution" Function on display page

### ISSUE THREAD

**Issue by robmyers** [creativecommons/mp#18]
Use clipboard.js from a CDN.

**Comment by robmyers** [comment]
Implemented. This won't work on older browsers (and current Iceweasel...).

The copied text deliberately ends with a newline so that it pastes into text editors in an unsurprising way. If this is actually surprising we can remove it.

**Comment by zenorocha** [comment]
clipboard.js creator here. Let me know if you need something.

**Comment by robmyers** [comment]
Hi @zenorocha . Nothing at the moment but thank you for clipboard.js!

**Comment by zenorocha** [comment]
;)
