### ISSUE TITLE
Changing the license on an image doesn't take me anywhere

### ISSUE THREAD

**Issue by mattl** [creativecommons/mp#2]
Amstrad PCW512, running a browser made of cat hair and string.

**Comment by robmyers** [comment]
@mattl  Please pull the latest commit or try the version on rob.tech at /mp/ , this should be fixed.

**Comment by mattl** [comment]
Nope.

Leaves me on the same page where I can change the license again and again and again.

**Comment by robmyers** [comment]
Where should it take you? Changing the license is so cool I assume the user will want to do it as much as possible. We should gamify it, give them a star for each time they change a license. Two for changing to NC-SA.

**Comment by robmyers** [comment]
It now redirects to the display page.
