### ISSUE TITLE
Add link to About CC section in following places

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/mp#21]
?action=browse
?action=search

text for should be something like "What is Creative Commons? Learn more[link]"

?action=new

text should be something like "Learn more about the licenses"

**Comment by robmyers** [comment]
Added in next version. This is currently below the list of licenses so it's immediately above the "about CC" ink in the footer and linked to the same location.

If this is not OK I can move the link higher, or remove it and rename "About CC" in the footer to "What Is Creative Commons" or "About Creative Commons".
