### ISSUE TITLE
nix categories on search

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/mp#23]
I would do same categories on upload as search, so at ?action=search

Nix FC category and add CC licenses

Also, does "Any" include ARR copyright?

**Comment by robmyers** [comment]
Any does include ARR, at the code level we just ignore that column completely.

**Comment by janeatcc** [comment]
Good! Might be worth clarifying that it is under any terms, not just any license then. The model doesn't seem to be up for me to click through anymore so let me know when it's ready for another round of feedback..

**Comment by robmyers** [comment]
Option changed to "Any Terms" in next version.
