### ISSUE TITLE
copy attribution button doesn't work

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/mp#28]
as discussed on call, flagging here to keep track

**Comment by robmyers** [comment]
Which browser model, please? I checked it on the latest firefox and it's OK, scripted but copy to clipboard is a new technology in web browsers. It should fall back to displaying a text field for the user to copy from if the clipboard fails.

**Comment by mattl** [comment]
needs to not use relative links

**Comment by robmyers** [comment]
@mattl Implemented in next version.

**Comment by janeatcc** [comment]
can't test now b/c model is not up

**Comment by mattl** [comment]
you may need to hit up the src/ directory

**Comment by janeatcc** [comment]
chromium Version 45.0.2454.99 (64-bit)

**Comment by robmyers** [comment]
Oh that should be supported (as of Chromium 43):

http://caniuse.com/#feat=clipboard

The way it is meant to work is:

1. The user clicks on the "Copy Attribution" button.
2. Where the clipboard is supported, the code copies the attribution string to the clipboard. Where the clipboard is not supported, it shows a text field allowing the user to copy the attribution manually.
3. The user can now paste the attribution string into e.g. a text document or the address bar.

If it is not possible to paste the attribution string after pressing the button and the text area does not show instead that is a bug. Please can you see if there is anything in the JavaScript logs? They can be accessed using Command-Option-J in Chromium.

Possibly we should alert the user when copying is successful but that's not particularly effective to do just with Bootstrap.

**Comment by janeatcc** [comment]
Got it. It works. But it is not obvious to the user what is happening. Can some kind of notice be given that attribution has been copied to clipboard?

**Comment by mattl** [comment]
Suggest maybe change the button class?

**Comment by robmyers** [comment]
We now pop an alert area under the Copy Attribution button that tells the user they have copied successfully.

It would look better above or beside the button, but above would move the button and might cause the user to click in the wrong place, and beside would end up under the button anyway on smaller devices.
