### ISSUE TITLE
drop-down search and browse filters indents mis-aligned

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/mp#29]
on both search and browse, see

<img width="439" alt="model indent" src="https://cloud.githubusercontent.com/assets/6394777/11876162/0dfbd520-a49d-11e5-93de-ebfcdec180c4.png">

**Comment by mattl** [comment]
Fixed.

**Comment by janeatcc** [comment]
Cool, doesn't update for me but I assume it does in the final.

**Comment by janeatcc** [comment]
actually, still misaligned when i try another browser.

**Comment by mattl** [comment]
Fixed in the code, not live yet.
