### ISSUE TITLE
markdown - expandable sections

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/mp#30]
Can we add support for this, or does this already work with markdown on Github? Need it for actual [toolkit text](https://github.com/creativecommons/mp/blob/master/platform-toolkit.mdwn), default to hide some lengthy sections. 

http://answers.squarespace.com/questions/16924/how-do-i-create-hideshow-text-on-a-page-like-you-see-with-faqs

**Comment by mattl** [comment]
This isn't something I believe Markdown supports.

**Comment by janeatcc** [comment]
What's an alternative then? HTML? Would rather do in html if it supports it b/c this is something we need for toolkit.

**Comment by robmyers** [comment]
The example given is something we can do, with two constraints:

1. It has to apply to *every* block of text under e.g. a level 2 header (## or ------- in Markdown). We cannot exclude some level 2 headers, it has to be all or nothing. But it could be level one headers or some other block marker instead.

2. It will not work in the Markdown file itself, only when the Markdown file is rendered to html.

To do this, we would have a /doc/ folder that contains:
doc.md
Makefile
doc.html

where doc.html is generated from doc.md by the Makefile.

If this is acceptable let me know and I'll implement it.

**Comment by janeatcc** [comment]
Ok let's apply it to a block marker that is unique and won't be used for anything else. That or all level 5 headers or something. 

This seems acceptable to me. Do I need to recreate https://github.com/creativecommons/mp/blob/master/platform-toolkit.mdwn or just move it inot the folder you're talking about?

**Comment by robmyers** [comment]
Added for h2s, but we can target another header instead if preferred. We cannot target a particular block marker (e.g. class="collapse")without adding html to the markdown.

I've moved platform-toolkit.mdsn and added some lorem ipsum to demonstrate the effect.

**Comment by janeatcc** [comment]
We don't want it for H2's. Can you make it for H5's or H4's? It will only apply to certain sections.

**Comment by robmyers** [comment]
It has to apply to all sections of the same kind at present. We can apply to h5s or h4s as desired, those are #### or ##### in markdown. Or if we got to html we can target arbitrary areas, but then we lose the simplicity of markdown. Maybe let's see how a more finished version of the document looks then work out which level is best to target?

**Comment by janeatcc** [comment]
Sure, but I say H5's so I can just use all the previous headers for
non-expandable sections.

On Thu, Dec 17, 2015 at 5:38 PM, Rob Myers <notifications@github.com> wrote:

> It has to apply to all sections of the same kind at present. We can apply
> to h5s or h4s as desired, those are #### or ##### in markdown. Or if we got
> to html we can target arbitrary areas, but then we lose the simplicity of
> markdown. Maybe let's see how a more finished version of the document looks
> then work out which level is best to target?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/mp/issues/30#issuecomment-165633558>.
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by janeatcc** [comment]
Ok, I've added here https://github.com/creativecommons/mp/blob/master/doc/platform-toolkit.mdwn.

The sections we want to hide and click to expand are:

Content owned by your users:
Content owned by the platform: 
Third party content contributed to the platform: 
In the most simple and accessible terms possible, the TOS should explain how CC licensing works for content creators on the platform. 
The TOS should make it clear that users of the platform can reuse CC-licensed content according to the terms and conditions of the applicable license.
The TOS should state in clear terms what types of existing CC-licensed content (created by third parties and not the user) can be uploaded by users and how that content should be marked.
Learn more.
Model platform TOS provisions: 
Real world TOS provisions 

I think I marked most with H5, eg. #####

**Comment by janeatcc** [comment]
Hey @robmyers, what's the status of this? Can we resolve this Monday?

**Comment by robmyers** [comment]
The h5 elements don't look like titles with their default styling. So when the content under them is collapsed they just look like orphaned sentences.

I suggest not using the collapse at that level. So either moving it to somewhere between h1..h4 or (probably my preferred option) not using it.

**Comment by janeatcc** [comment]
I can't move to h4 b/c we have headings under h4. And all the other H1-h4
are in use for navigation links. How about if we use H5 but also add in the
title (show/hide) or other explanatory text that makes it obvious that the
section is expandable? We definitely need collapsable secdtions for the the
ultimate styled webpage.

On Mon, Dec 21, 2015 at 10:15 AM, Rob Myers <notifications@github.com>
wrote:

> The h5 elements don't look like titles with their default styling. So when
> the content under them is collapsed they just look like orphaned sentences.
>
> I suggest not using the collapse at that level. So either moving it to
> somewhere between h1..h4 or (probably my preferred option) not using it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/mp/issues/30#issuecomment-166380082>.
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by robmyers** [comment]
I have made the h5 text bold, added a triangle before it, and made it so it turns blue and underlines like the old visual style of a hyperlink when the mouse pointer is moved over it. We couid add some show/hide text with javascript, I didn't think of that before. Let me know if that is preferable or if it should be added.

You can see the current results at tech.../mp/doc/platform-toolkit.html

**Comment by janeatcc** [comment]
Yes, that works. Let's make sure that will happen for each h5 heading (as I
think some large chunks of text disappearing under the first one under
Checklist).

On Mon, Dec 21, 2015 at 11:37 AM, Rob Myers <notifications@github.com>
wrote:

> I have made the h5 text bold, added a triangle before it, and made it so
> it turns blue and underlines like the old visual style of a hyperlink when
> the mouse pointer is moved over it. We couid add some show/hide text with
> javascript, I didn't think of that before. Let me know if that is
> preferable or if it should be added.
>
> You can see the current results at tech.../mp/doc/platform-toolkit.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/mp/issues/30#issuecomment-166398802>.
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by robmyers** [comment]
Chunks were disappearing, thank you for reporting that. I have fixed that bug. Please see tech../mp/...

**Comment by janeatcc** [comment]
Looks good. I rearranged some text so that some of the chunks wouldn't
disappear.

On Mon, Dec 21, 2015 at 12:24 PM, Rob Myers <notifications@github.com>
wrote:

> Chunks were disappearing, thank you for reporting that. I have fixed that
> bug. Please see tech../mp/...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/mp/issues/30#issuecomment-166408374>.
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by robmyers** [comment]
OK cool. I'm glad that's working now.
