### ISSUE TITLE
take screenshots of model once final

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/mp#32]
@robmyers let me know when it's pushed out in final shape (with issues resolved) so i can take screenshots

**Comment by mattl** [comment]
I'll take em. I can get the sizes perfect.

**Comment by janeatcc** [comment]
Cool. Wanna send them over to me once you have them?

**Comment by janeatcc** [comment]
Hey @robmyers -- I think the model platform is all done now right? @mattl, do you think you can send me those screenshots Monday? If not, I'll take them. Need to close this out Monday and send final update to WMF. Thanks!
