### ISSUE TITLE
License Explanation Panel

### ISSUE THREAD

**Issue by robmyers** [creativecommons/mp#33]
@mattl @janeatcc I'm worried that the panel under the license choosers that lists all the licenses and highlights the one the user currently selected takes up too much space/is too intrusive as an example. Should we roll this information into the drop-down menu, show just the information for the currently chosen license, or is the current behaviour good?

**Comment by janeatcc** [comment]
I agree. Those search and browse pages should really just have a link to the About CC page. And at most just the highlighted filter.

**Comment by robmyers** [comment]
@mattl ?

**Comment by mattl** [comment]
agreed. link it up yo.

**Comment by robmyers** [comment]
We could move "What is creative commons learn more<LINK>" next to the "License" title as "About the liceses" or "Learn more" or "Help".

![aboutcc2](https://cloud.githubusercontent.com/assets/21746/11887267/65af4866-a4e7-11e5-9569-afe012d71bb3.png)

Or we can keep it under the browse button.

![aboutcc1](https://cloud.githubusercontent.com/assets/21746/11887270/6bf3a956-a4e7-11e5-96ae-9457bad2ab5c.png)

It's currently underneath, let me know what you think.

**Comment by janeatcc** [comment]
I like the first -- moving up to next to License.

On Thu, Dec 17, 2015 at 5:56 PM, Rob Myers <notifications@github.com> wrote:

> We could move "What is creative commons learn more" next to the "License"
> title as "About the liceses" or "Learn more" or "Help".
>
> [image: aboutcc2]
> <https://cloud.githubusercontent.com/assets/21746/11887267/65af4866-a4e7-11e5-9569-afe012d71bb3.png>
>
> Or we can keep it under the browse button.
>
> [image: aboutcc1]
> <https://cloud.githubusercontent.com/assets/21746/11887270/6bf3a956-a4e7-11e5-96ae-9457bad2ab5c.png>
>
> It's currently underneath, let me know what you think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/mp/issues/33#issuecomment-165637876>.
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by robmyers** [comment]
Moved, see tech .. /mp/src/?action=search for an example.

**Comment by robmyers** [comment]
Thank you for everyones input on these. :-)
