### ISSUE TITLE
Allow for the uploading of text documents, videos and sounds

### ISSUE THREAD

**Issue by mattl** [creativecommons/mp#4]
* Text Documents should just be Markdown stored in a file on disk.

Videos and sounds should just be blobs on disk. Let's assume common formats and not check for now. Don't allow people to upload viruses, PDFs and php files ;)

**Comment by robmyers** [comment]
Can we avoid text for now?

**Comment by mattl** [comment]
Okay

**Comment by robmyers** [comment]
Added in 2f88096 .

**Comment by robmyers** [comment]
Markdown isn't rendered, that would require an extension.

We also can't easily differentiate between ogg audio and ogg video, so all ogg is treated as video. This allows it to play but we use the wrong icon for example.

**Comment by mattl** [comment]
Can you remove the item with the JavaScript in it from my items?

**Comment by robmyers** [comment]
No. You've only yourself to blame.

**Comment by robmyers** [comment]
OK, removed.
