### ISSUE TITLE
please add images to github folder

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/mp#40]
Gdrive folder with images: https://drive.google.com/drive/folders/0B8aD_Zr0ZfRBNkJHRU9WYzFFSzQ

Github folder: https://github.com/creativecommons/mp/tree/master/doc/images

**Comment by janeatcc** [comment]
please also add the images in this subfolder: https://drive.google.com/drive/folders/0B8aD_Zr0ZfRBU2tHSG95bDNyYlU

**Comment by robmyers** [comment]
Should the subfolder be copied as a folder, or should the images be copied into the images folder?

If it should be a subfolder please can we remove the spaces from the name, e.g. change it to OtherPlatformImages.

**Comment by robmyers** [comment]
Added, and added. :-)
