### ISSUE TITLE
batch uploads in model platform

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/mp#41]
is that a function in it currently? if not, could we add that down the line?

**Comment by robmyers** [comment]
We have batch *relicensing*, that's linked from the profile page via the "Change licenses" button.

We don't have batch licensing as in "I have a folder with lots of images that I wish to upload under the same license and attribution terms, for example for my Museum, and I need an efficient interface to manage that process".

If the latter is required, how urgent is it? I can see how to do it, I'd just need to claw back some time to write the code. :-)

**Comment by janeatcc** [comment]
Yes -- that is default licensing versus batch licensing IIRC.

I wouldn't say it is urgent, but it would be good to have when we publish the HTML version of the toolkit in February. Basically it is illustrating this section of the toolkit (currently using a Flickr screenshot): https://github.com/creativecommons/mp/blob/master/doc/platform-toolkit.mdwn#batch-licensing-for-multiple-works

**Comment by robmyers** [comment]
Sorry for still not quite getting it - it's the batch *upload* that is
missing, as opposed to the batch *license changing*
, and we need the uploading functionality?

**Comment by janeatcc** [comment]
Ah, no I was the one who misunderstood. I see you can batch relicense. You can't batch upload, but if you could batch upload, you would be able to license the batch in one go. 

I don't think it's a priority to add this to the model platform if it's going to take a whole bunch of new code. I would mark this as nice-to-have. If Flickr ever goes under, we can rethink then and add a batch upload/licensing feature to this model to replace that example.

**Comment by robmyers** [comment]
@mattl Has this been prioritised?

**Comment by mattl** [comment]
No, it was just unassigned to anyone.

**Comment by robmyers** [comment]
OK cool. :-)
