### ISSUE TITLE
Metadata for display section could use some additions for multiple media files/per page

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/mp#42]
You could add additional html per attribution statement to connect the attribution to a particular media file. This is useful for search engines and other machine readers, as they cannot determine which file is described by the RDFa. The CCrel primer talks about adding a div with an about tag.

```
<a rel="license" href="http://creativecommons.org/licenses/by/3.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/3.0/88x31.png" /></a><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Lawrence Lessig at the CC Global Summit 2015</span><a xmlns:cc="http://creativecommons.org/ns#" href="https://vimeo.com/143427866" property="cc:attributionName" rel="cc:attributionURL">Creative Commons</a>
```
to something like:
```
<div about="<LINK TO MEDIAFILE>">
	<a href="http://creativecommons.org/licenses/by/3.0/" rel="license"><img alt="Creative Commons License" src="https://i.creativecommons.org/l/by/3.0/88x31.png" style="border-width:0"></a><span>Lawrence Lessig at the CC Global Summit2015</span><a href="https://vimeo.com/143427866" rel="cc:attributionURL">Creative Commons</a>
</div>
```
as described in https://wiki.creativecommons.org/images/d/d6/Ccrel-1.0.pdf

**Comment by janeatcc** [comment]
I like this addition. So the text would be something like, 

"If you want to associate the CC license metadata with a particular media file, wrap the metadata in div tags. 

```
<div about="<LINK TO MEDIAFILE>">
    <a href="http://creativecommons.org/licenses/by/3.0/" rel="license"><img alt="Creative Commons License" src="https://i.creativecommons.org/l/by/3.0/88x31.png" style="border-width:0"></a><span>Lawrence Lessig at the CC Global Summit2015</span><a href="https://vimeo.com/143427866" rel="cc:attributionURL">Creative Commons</a>
</div>
```
_explanation_: about defines the subject of metadata within the div. Here we have about="", which
defines the subject to be the URL of the media file."

**Comment by mzeinstra** [comment]
Yes, that would do.

(although your explanation and code snippet are out of sync). 

Would be good to have this in the model platform code as well.

**Comment by janeatcc** [comment]
What about the code snippet - can you specify? I just copied and pasted over yours. :)

**Comment by mzeinstra** [comment]
And I copied it from https://wiki.creativecommons.org/images/d/d6/Ccrel-1.0.pdf :)

I think your snippet is fine to communicate the idea to developers of the platform.

**Comment by janeatcc** [comment]
Ok, I'll clean up and have matt and rob do another review before updating.

**Comment by robmyers** [comment]
Yes this is great, thank you mzeinstra. Shall I add this to the code as specified or do we need to discuss further?

**Comment by janeatcc** [comment]
If it looks good to you @robmyers, I would go ahead and add as an additional example of code to that section of the toolkit with prefatory and explanatory text like I added above, eg. "We recommend that you associate the CC license metadata with a particular media file because... This is how you do that.. "

**Comment by janeatcc** [comment]
Added this at https://github.com/creativecommons/mp/blob/master/doc/platform-toolkit.mdwn#metadata-for-display under "Code associating metadata to a specific media file:" heading

@robmyers @mzeinstra can you take a look?

**Comment by mzeinstra** [comment]
Looks fine to me.

Only thing I would add is an example of the benefit of additional metadata. For example rel=license might help your content to reach higher in the image search of google when their advances search is set to the cc license.

**Comment by janeatcc** [comment]
Good suggestion - I added a line to that effect here: https://github.com/creativecommons/mp/blob/master/doc/platform-toolkit.mdwn#license-metadata
