### ISSUE TITLE
Logos and icons: should we promote the use of the CDN hosting the logo's? 

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/mp#43]
You are able to number of times a cc icon is loaded from your CDN, should this guide promote the hotlinking of those images over downloading them for the use on platforms?

**Comment by janeatcc** [comment]
Good question. @robmyers created this set of circular icons for linking, like we link to the buttons when people choose to license from our chooser: https://licensebuttons.net/i/cc-gift-guide/.

However when it comes to platform use, platforms have never used linking to buttons, but tend to download and customize the icons to fit the design of their user interface. I'm hesitant to prescribe hotlinking in the toolkit for this reason, though we can revise the language to recommend it if they choose one of the gift guide set. Thoughts?

**Comment by mattl** [comment]
We can offer it if they'd like it, I suspect most won't, but perhaps smaller platforms or free software projects will.

**Comment by mzeinstra** [comment]
to be able to measure the impact of platforms would be a great asset, offering it to platforms would not make it more complicated. 

I agree with Matt that most platform would probably copy the files, but every hit on those files counts for the state of the commons.

**Comment by janeatcc** [comment]
Ok, we should recommend in the toolkit at least. Is the gift guide circular logos the set to get people to link to, or will we be creating a different set @mattl @robmyers ?

**Comment by mattl** [comment]
I'd like to create a bunch in a variety of sizes and colors and host all of
them.

@robmyers we have the script for that now, right?

**Comment by robmyers** [comment]
I agree that it would be very good to measure usage this way, although people may have privacy concerns.

The script works, we're using it for the Model Platform. It needs tidying up (some of the layout logic is fragile now I've modified it), and if we are offering fixed sizes we should probably replace or wrap it with more of a build system.

**Comment by mattl** [comment]
I'd like to generate static PNG in 255 color variations with white, black,
grey and transparent backgrounds, in say... 10, 12, 16, 24, 32, 48 and 64
px heights for each of the license combos and deeds.

Any other variants you can think of too.

Organize them by color/height/license..

ie. licensebuttons.net/i/000000/16/by-sa.png

Sure, we don't think may of them will be used, but let's not worry about
that.

**Comment by robmyers** [comment]
Is it worth making a build system for this, or should we just stick the script behind (e.g.) Varnish?

**Comment by mattl** [comment]
Yeah, make something... but just run it, generate all the images and put
them on the server. CF will CDN them for us.

**Comment by janeatcc** [comment]
@robmyers How's this going?

**Comment by robmyers** [comment]
It didn't. I'll look at it now.

**Comment by robmyers** [comment]
@janeatcc @mattl

I've got a build system created. I'm just fine-tuning some of the numbers in the layout code.

Would we ever have a background colour that isn't simply transparent? People could add a background colour with css if needed.

The current image path format is based on the existing one, with colour information added -

l/by-nc-sa/4.0/88x31-00000000-ffffffff.png

where 00000000-ffffffff is transparent white and opaque black respectively. We could use named colours instead and always have the background transparent to simplify this.

**Comment by janeatcc** [comment]
I think having the background transparent is good. Not sure as I can't see it -- do I add that to a url?

**Comment by mattl** [comment]
My email reply didn't come through, but I said:

I'd like us to provide every color combination we care to, in a folder structure and in a variety of sizes.

Yes, many of them may be a little redundant, but it's easier to just load them all up on licensebuttons.net and provide that as a service to people.

**Comment by mattl** [comment]
I think there's usefulness to providing multiple background colors, this stuff needs to be easy and not rely on CSS.

**Comment by robmyers** [comment]
![88x31-ffffff00-000000ff](https://cloud.githubusercontent.com/assets/21746/12653936/947782f0-c5a6-11e5-9c3f-36e28b9bfcc8.png)
^embedded example (with the file name completely changed by uploading to GitHub).

**Comment by mattl** [comment]
Also Rob, the reason for the folder structure is to prevent having a folder with tons and tons of files in it.

**Comment by janeatcc** [comment]
Nice. I think we should do transparent on top of the other colors. I imagine that might get used/customized by the platform most.

As for sizes, can we do some standard sizes based on what platforms are doing? eg. let's look at Vimeo, YouTube, Medium, Flickr. Also can we do sizes for mobile?

**Comment by mattl** [comment]
How do you imagine mobile sizes working? The intention is to make this image clickable, right?

**Comment by janeatcc** [comment]
Yes, linked to the license deed, as with the buttons.

**Comment by robmyers** [comment]
@mattl: OK two colours it is. :-) Regarding folder structure, the un-asked part of my question is whether we should make the colour names into one or two levels of folders, or maintain the current folder structure.

**Comment by robmyers** [comment]
I shall add more sizes.

How do people feel about named (e.g. html named) colours?

**Comment by mattl** [comment]
Just two? I was imagining at least four... white, black, "grey" and transparent.

Structure would something like.... background/foreground/size/cc-by-sa.png

so 000000/ffffff/32/cc-by-sa.png gives you a 32x32px white on black by-sa image.

I'd say no to named colors :-1:

**Comment by janeatcc** [comment]
+1 on the white, black, grey, and transparent!

**Comment by robmyers** [comment]
The two are foreground and background, as in your example. I agree about the order of background/foreground, although it might make more sense cognitively to have the colour of the logo *first*, i.e. foreground/background. So "I'm looking for a red logo, so.. /l/ff0000ff/...".

Also note the use of alpha (the last two bytes).

The sizes are currently rectangular, 80x15 and 88x31. Flickr are using 76x22. Vimeo are variable width, each icon is 40x40. So are Medium, each icon is 20x20. YouTube use a text link.

Given this should we also provide individual license module icons, or will this mislead people into thinking that we are offering e.g. the old SA license with no attribution?

**Comment by mattl** [comment]
I'm going to respond to this in full after class, but we shouldn't be providing the single icons. 

I think the alpha bytes are confusing, if an interesting hack ;)

**Comment by robmyers** [comment]
If we make the images always opaque we can lose the alphas. It's just that we're then not able to integrate with background-gray-number-354432523 on someone's new site and they'll generate the icon themselves.

**Comment by mattl** [comment]
We do want transparent :)

It should be a background-color though.

**Comment by robmyers** [comment]
Totes. So we can either represent that with a name ("transparent"), by adding the alpha byte just to the background(/l/000000ff/000000/), or by having a rule that white backgrounds are always transparent (which will upset people who want opaque white).

**Comment by mattl** [comment]
Yeah, I think transparent or alpha is fine for a name there.

**Comment by robmyers** [comment]
Cool.

**Comment by janeatcc** [comment]
YouTube uses it in its audio library: https://www.youtube.com/audiolibrary/music

**Comment by robmyers** [comment]
Ah I missed that, thank you. It's 24x23.

**Comment by mattl** [comment]
I would imagine that would be an edge case where we'd provide a single license image, but typically we'd only produce a fixed sized image (centered) for all the licenses, right?

ie. a 32x80 (or whatever it is) pixel image that has 1, 2 or 3 license icons arranged in it?

**Comment by robmyers** [comment]
Yes, centred within the horizontal rectangle.

Path format on license button server:

p/mark/1.0/88x31.png

Current path format:

p/public-domain-mark/1.0/transparent/ffffff/88x31.png

**Comment by mattl** [comment]
What's 1.0? License version? 

We should probably also do Euro and Yen versions of NC, too...

**Comment by robmyers** [comment]
It is the version.

The Euro/yen symbol is in the font and I agree we should support it. Any mention of nc should expand to all three, so we get three images the same except for the currency symbol.

We can add -e and -y to the file name to differentiate them.

**Comment by mattl** [comment]
I dunno if the version matters, given that they're identical images ;)

**Comment by robmyers** [comment]
Will remove version.

**Comment by robmyers** [comment]
Again, copying the current format. :-)

**Comment by mzeinstra** [comment]
Sounds like a great idea. Will you catch 404s and have a script make these logo's on the fly?

**Comment by robmyers** [comment]
We're planning to just generate a ridiculous number of colours. Lazy creation might be more efficient though.

**Comment by mattl** [comment]
The server is so widely trafficked, I don't want us to generate anything on
the fly.

**Comment by janeatcc** [comment]
Are these ready? Currently the link I have provided in the toolkit is to https://licensebuttons.net/i/cc-gift-guide/. Should I replace that with something else?

**Comment by mattl** [comment]
@robmyers -- would be good to know what's up with these

**Comment by robmyers** [comment]
See private repo. We can generate and move into position. Which server?

**Comment by janeatcc** [comment]
Where are we on this? I need to give some logos for a mobile app to a DOE platform. Should I point them to a gift guide or are some of these ready to share?

**Comment by mattl** [comment]
I believe we have them, we just need to upload them.

**Comment by janeatcc** [comment]
Cool. When do you think we can do that?

**Comment by robmyers** [comment]
@janeatcc There's a problem with some of the two-icon buttons (by-sa, by-nd). I'm working on fixing this now but it will take several hours to rebuild and upload the buttons.

**Comment by mattl** [comment]
rob, let's upload the ones we have for now... ping me on IRC and I'll get this going, as there's a lot of them.

**Comment by robmyers** [comment]
@mattl I've put a fix in the git repo. Pinging.

**Comment by mattl** [comment]
https://licensebuttons.net/i/
