### ISSUE TITLE
ready to start moving toolkit to a cc.org webpage

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/mp#44]
Can we link up https://github.com/creativecommons/mp/blob/master/doc/platform-toolkit.mdwn to a page that exists on cc.org, nicely formatted with expandable sections as we discussed last month? I'll start editing again once there is a preview page I can see..

**Comment by mattl** [comment]
How important are the expandable sections? Asking for a friend.

**Comment by robmyers** [comment]
Also - @mattl would this be a WordPress page, or something we'd want to roll into the static version of the site, or is this something that needs doing before that?

**Comment by janeatcc** [comment]
Pretty important. Right now it is all a long block of text that is daunting to any platform wanting to integrate. We want to ease them into it! Design is crucial here. Only enough info at a time.

**Comment by mattl** [comment]
Maybe split it into sub pages?

**Comment by janeatcc** [comment]
Then the subpages would never get read.

**Comment by mattl** [comment]
A page for each section that would be expanded seems reasonable.

**Comment by janeatcc** [comment]
It does, but I like how we're doing things all on one page, like with SOTC. It's more likely that someone will scroll quickly through one page to find what they want (with navigational links to help direct them) than go back and forth between a lot of dif pages that exist in dif urls. The latter seems more like a book. We want this to be a quick one-stop toolkit.

**Comment by mattl** [comment]
You have a choice right now: one page with no expandable regions, or a half dozen pages.

That's what we can do right now.

**Comment by mattl** [comment]
Multiple pages is what I'd expect when trying to implement something, look at any of the platform API documents.... lots of pages.

**Comment by janeatcc** [comment]
If we do one page, can we do a link after each major heading to navigate back up to the top (eg. TOC area)?

**Comment by janeatcc** [comment]
The collapsible sections are possible in Rob's version in html on his test site that we did last month. Is it because it is not possible on cc.org?

**Comment by mattl** [comment]
If you want to add 'back to top' links, you can... i wouldn't, i'd assume the back button in a browser is sufficient.

And yeah, we don't have a way to support them right now. I'm going to check in a version of the page in HTML now, you'll note that the TOC is generated for you, which is probably better than maintaining your own.

**Comment by mattl** [comment]
https://github.com/creativecommons/mp/commit/e328fee5ddd4e6ecb07c3ed08724a5a9e096311d

Jane, do you have a local copy of the repo?

**Comment by janeatcc** [comment]
Like on my desktop via GitHub app? Yeah.

**Comment by mattl** [comment]
Okay, cool... update your local copy and take a look at platform-toolkit.html in your browser. You should see it in a CC webpage style.

**Comment by janeatcc** [comment]
You mean on Rob's server?

**Comment by mattl** [comment]
No, from your computer.

**Comment by janeatcc** [comment]
Nice. Where can I start editing it?

**Comment by mattl** [comment]
You don't edit the HTML file, you just edit the markdown file as before.

The HTML file is generated.

**Comment by janeatcc** [comment]
Ok, so edit the markdown file here on Github and view html in browser after I update my local repo for previews. Then when final, it will get generated on cc.org?

**Comment by mattl** [comment]
For now, you'll need to let me know when you've made a bunch of changes to the Markdown so I can regen the HTML. This will be more automated soon, and yeah, then there'll be some process to get it on creativecommons.org

**Comment by janeatcc** [comment]
Ok, though seems rather complicated versus me just editing on cc.org WP directly. 

I'll let you know when I've made a significant round of edits in Markdown.

**Comment by mattl** [comment]
Rather than editing a WordPress page, you edit a Markdown file on GitHub instead, that's the only difference.

**Comment by janeatcc** [comment]
Plus the addition of extra middleman steps to see what it actually looks like, versus just refreshing directly in WP.

**Comment by mattl** [comment]
There's a Preview tab in GitHub for your content, the rest is just setting up a process to do it :) 

Making things work well takes time. I'm working on this.

**Comment by janeatcc** [comment]
I know but that's not in CC formatting. But yeah, I will give up this battle. Looking forward to getting this up.

**Comment by mattl** [comment]
I hope it's not a battle :)

You shouldn't need to worry about "CC formatting" -- instead your content should be well structured and formatted, which you can see via the Preview in GitHub (or anything else you want to use to edit Markdown)

But yeah, I agree a preview is useful before publishing. That's what I'm working on.

**Comment by janeatcc** [comment]
Made another round of edits. Can we refresh the html? Also, the images aren't showing up in the html. Let me know how to fix!

**Comment by mattl** [comment]
The images are being embedded as GitHub pages, not the raw images.

https://raw.githubusercontent.com/creativecommons/mp/master/doc/images/Model%20default%20license.jpg is an example of the correct URL.

I'll update the HTML now.

**Comment by janeatcc** [comment]
@mattl so is this the right way to put it?

![Model default license](https://raw.githubusercontent.com/creativecommons/mp/master/doc/images/Model%20default%20license.jpg)

**Comment by mattl** [comment]
Yeah, that looks like it works.

**Comment by janeatcc** [comment]
Ok, another round of edits. Could you refresh html?

**Comment by janeatcc** [comment]
<img width="1197" alt="images broken toolkit" src="https://cloud.githubusercontent.com/assets/6394777/12927393/e1dbde86-cf1c-11e5-85bd-31567ce8ddf3.png">

**Comment by janeatcc** [comment]
How can I get the name of the image to not show up in the html version? See screenshot. It doesn't show up in Github preview though:

<img width="701" alt="image name toolkit" src="https://cloud.githubusercontent.com/assets/6394777/12927690/53d81f8a-cf1e-11e5-9216-7cfd50fd855a.png">

**Comment by mattl** [comment]
Those are fixed in the new version -- pandoc, was adding them to the markup. I've disabled that and added the build script for reference.

**Comment by janeatcc** [comment]
Updated logos link! Now good to put on cc.org. What should the url be? maybe platform/toolkit? Fyi that cc.org/platform is reserved for the landing page for the initiative.

**Comment by mattl** [comment]
creativecommons.org/platform/model-platform or something.

If it's reserved you should probably reserve it :)

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by janeatcc** [comment]
Well I already have the page drafted -- isn't that reserving enough?

I don't think model-platform as it's the toolkit, not model platform. let's do cc.org/platform/toolkit please!

**Comment by mattl** [comment]
I guess it matters a bit less now we have the blog seperately, but if you
have a page in mind, can be worth just making a placeholder page there in
WordPress. I do it for @tvol all the time with campaigns and things.

**Comment by janeatcc** [comment]
You mean a public placeholder page? The private placeholder page is already there.

**Comment by janeatcc** [comment]
So this is ready to be moved. You'll see https://creativecommons.org/platform/ is already in private draft. Can you add the toolkit to a new page https://creativecommons.org/platform/toolkit? Let me know when it's up and I can do copyedit to make sure everything's in its right place.

**Comment by janeatcc** [comment]
Can we try and get this up this week since it's low-hanging fruit? Unless the website redesign is imminent (eg. in the next month). I'm sending the link to the Github version (which doesn't have the TOC b/c I stripped I for WP) to platforms more frequently so it's just a big block of text ATM. Would be good to send them to .org page with TOC.

**Comment by mattl** [comment]
K, done. https://creativecommons.org/platform/toolkit/ -- please make new issues for any updates that need to happen, and you can just edit the markdown here on GitHub, and I'll generate a new page and push it up.
