### ISSUE TITLE
re: other considerations for TOS

### ISSUE THREAD

**Issue by tvol** [creativecommons/mp#46]
"the direct license to the platform is in conflict with the CC license" - not how i read it. if the license is for the platform provider itself (which i think it normally is) it just sits alongside the CC license. the problem is if they introduce something in the TOS that then affects how their users of the service can leverage the CC licensed content in a way that is more restrictive than what the license says--that's a problem and you address it below.

**Comment by sarahpearson** [comment]
Actually, that's a separate issue than what I'm trying to get at here. Simply asking for a license from the uploader is a conflict when it comes to them uploading CC-licensed content they don't own. That's sub-licensing, which is prohibited by CC licenses.

**Comment by janeatcc** [comment]
@tvol Do you get it now?
