### ISSUE TITLE
re: learn more section under "Most common conflicts in terms of service"

### ISSUE THREAD

**Issue by tvol** [creativecommons/mp#48]
saying "creative commons" needs to be removed if they impose other contractual restrictions--surely this is true, but seems to negate them even attempting to integrate CC in the first place. how can we address this better?

**Comment by janeatcc** [comment]
@sarahpearson can you address?

**Comment by sarahpearson** [comment]
@tvol Just above, we say that we strongly discourage the practice and that it undermines the purpose of the licenses. Beyond that, I'm not sure what else to do. If we can't convince people not to do it, the trademark is our only stick.

**Comment by janeatcc** [comment]
@tvol Does this resolve your issue? Let me know so I can revise.
