### ISSUE TITLE
change links such as http://creativecommons.org/ns to https?

### ISSUE THREAD

**Issue by tvol** [creativecommons/mp#50]
does it matter?

**Comment by janeatcc** [comment]
I don't know. Does it @mattl @robmyers ?

**Comment by mattl** [comment]
Anytime anyone at Creative Commons publishes a link to creativecommons.org
it should be HTTPS. If things don't work on that page for whatever reason,
fix them or if you can't, ask me or Rob to fix them. HTTPS-only is the way
things are heading.

**Comment by janeatcc** [comment]
Ok, will change.
