### ISSUE TITLE
Static use of Creative Commons materials

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/mp#51]
I received a question from a startup using CC licensed photos on their website. They are not a content provider/platform but a tourism agency for a particular region. 

Can we add instructions on how to add static images to your webstite. Like how to attribute a CC BY image that is used in the footer or header of your website.

I recommended to make a separate page with a description an the license

````
The image in the footer is created by <name> and licensed under a <license name and link>
```` 

Can we add something like this to this project for platforms?

**Comment by janeatcc** [comment]
I don't think this is for platform integration toolkit, but for marking. See marking resources: https://wiki.creativecommons.org/wiki/Marking. Do you want to revise a section that is there?

**Comment by mzeinstra** [comment]
Hi Jane,

What I am missing on the marking page is the use are platforms that use CC as integral part of their system but are not content distributors. For example a travel agency that uses CC for the header and footer of their page. I think we should add an description about how to do proper attribution on a secondary page, like a page called copyright or colophon.

**Comment by mattl** [comment]
I think that's out of scope for a platform toolkit.

**Comment by janeatcc** [comment]
Yes, this is for marking wiki resources. You can move this issue to CC website I think: https://github.com/creativecommons/creativecommons.org/issues. Not sure who would take it up, but we can prioritize it there once it is filed.
