### ISSUE TITLE
new html version lops off "http" from links

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/mp#52]
eg. links now show up as "s://wiki.creativecommons.org/wiki/Marking" 

Intentional? Do I have go through and fix and add "http" back in front of them all?

**Comment by mattl** [comment]
Screenshot?

**Comment by janeatcc** [comment]
<img width="601" alt="broken links toolkit" src="https://cloud.githubusercontent.com/assets/6394777/12924279/2096cf14-cf0e-11e5-8290-90f5d8934070.png">


see lower left for the hyperlink

**Comment by mattl** [comment]
Looks like you changed them all here: https://github.com/creativecommons/mp/commit/d708d509879515ee5f6d736e3019e59f7879345d#diff-b7c9391938d375509dd16a1724756555
