### ISSUE TITLE
Redesign Platform Toolkit page

### ISSUE THREAD

**Issue by kgodey** [creativecommons/mp#53]
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Redesign the current version of CC’s platform toolkit webpage so that it looks clean and contemporary. Submit it as a pull request to this repository.

Usage of [CC Vocabulary](https://opensource.creativecommons.org/cc-vocabulary/) is recommended but not required.

**Comment by shwetadhuliya2018** [comment]
Hi @kgodey,
I would like to contribute to this issue.

**Comment by shwetadhuliya2018** [comment]
Hi @kgodey,
According to my understanding, Issue is to redesign this page- https://creativecommons.org/platform/toolkit/ . Please correct me if I am wrong.

**Comment by kgodey** [comment]
Yes, that's correct.

**Comment by shwetadhuliya2018** [comment]
Thank you for confirming. I will share a redesigned version soon.

**Comment by shwetadhuliya2018** [comment]
Thank you. I will share the design soon.

**Comment by ShanClayton** [comment]
Hi @kgodey,
I am an Outreachy applicant and would like to contribute to this issue as well.

**Comment by kgodey** [comment]
go ahead

**Comment by ShanClayton** [comment]
> go ahead

Great! Thank you. I will share it soon. Do we need to provide a mockup before we do a pull request?

**Comment by ShanClayton** [comment]
> go ahead

For clarification, am I submitting a mockup or would you like this coded?

**Comment by kgodey** [comment]
@ShanClayton Either is fine, this is just an exercise.

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this issue.
