### ISSUE TITLE
Mock up CC license workflow for a platform

### ISSUE THREAD

**Issue by kgodey** [creativecommons/mp#54]
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Create a mockup for how a website/content sharing platform that doesn’t currently offer CC licensing might introduce CC into their publishing workflow. Post your mockup here.

**Comment by apdsrocha** [comment]
Hi! I'm an Outreachy Applicant and I'd really like to try my hand at this task :)

**Comment by treasurechristain** [comment]
Hi! I'm Amadikwa Joy an outreachy applicant and I'd really like to contribute on this task.

**Comment by kgodey** [comment]
Go ahead, post your mockups here.

**Comment by discombobulateme** [comment]
Hi @kgodey! I would like to present a sketch... I'm working on an idea for this mockup (and I understand is missing lots of information still) based on simplifying the amount of text available on different parts of the website and wiki. My idea is to propose a mix between an infographic and a poster that could be transformed into a webpage as well (using cards for example). Before continuing I would like a feedback to know if that's what you had in mind when proposing this task, or if I should go into another direction :) . Just ask for some patience because it takes a while to connect all the information, understanding and simplifying.
![cc_platformSharing_mockup](https://user-images.githubusercontent.com/7980624/66272320-91b03d80-e868-11e9-844e-2197ce81bea4.jpg)

**Comment by kgodey** [comment]
@discombobulateme thank you for posting this! please give me a day or two to review it. also tagging @ericsteuer.

**Comment by kgodey** [comment]
@discombobulateme That's a great infographic, thank you! That covers how various content can be owned or licensed.

The specific issue here was for users selecting a CC license for their content e.g. see Medium's integration https://blog.medium.com/explicit-post-licensing-3aa1df783f8d but mockups of other parts of the platform toolkit are great too.

**Comment by discombobulateme** [comment]
Hi @kgodey :) That's a very nice article, thank you for the reference! I'll share with you and @ericsteuer in a bit a project on how to make all this information in a more intuitive way. The content in this previous mock up was just an idea on how to deal with a lot of information bit by bit, in a format that could be more static or for the user to interact in the website. Will work more and share the plan on google drive :)

**Comment by apdsrocha** [comment]
Hey @kgodey! Happy Sunday! :)  I've done a quick XD mock up of a Dribble-like interface trying to fit in a quick and easy licence selection process. Here's the link: https://xd.adobe.com/view/3056f702-9b1a-4216-7f74-e57e1321e5c2-4667/

Are you're interested in seeing my thinking process and UX/UI pattern studies? I'm bringing only XD sketches, but I could share the process here as well if it's important to you.  I'll be happy to have any feedback and see if you think I could expand on this little idea. Thank you so much!

**Comment by kgodey** [comment]
@discombobulateme sounds good!

@apdsrocha that looks great, thank you! (although those are not actually CC licenses, I assume they're just examples) I'd love to see your thinking process and UX/UI pattern studies as well. I think the next step here would be to be to actually use the six CC licenses and the terms they prescribe and see how that affects the choices.

This task is meant to be a piece of the research that would go into your internship, so hopefully this exercise will help with writing your final application.

**Comment by haatifi** [comment]
Hi @kgodey, so you would like to see a mockup that should demonstrate what options an end user has on a platform when they want to publish the work? Thanks! :)

**Comment by apdsrocha** [comment]
@kgodey thank you for looking over it! Cool, I'll organize and share the studies I've done so far. This was just a minor "trial run" to see how I'd go about structuring the task, I'm detailing every step that would be needed for the actual internship project. I've run into a few questions, but I'll head them over to the slack channel. Thank you again!

**Comment by annatuma** [comment]
@haatifi correct, imagine a user going to publish a work of some kind (image, video, text - anything) on a publishing platform, and think about the best way to build licensing options into the publishing flow.

@apdsrocha looking forward to reviewing your final application, the mockup you shared a few days ago was interesting.

**Comment by apdsrocha** [comment]
@kgodey @annatuma @ericsteuer Hey, happy Tuesday! I'm submitting here a study of everything I've done/seen so far, with a few broad ideas and how I think this task could be approached.  https://docs.google.com/presentation/d/13XqOtX7OZ70QxLHeJCf8TRoqibUEXgvabCWARgBksfI/edit?usp=sharing

I also set up a google docs (it's open for comments) to keep all the info, links, questions regarding my application. I've shared over slack and tagged you guys, but I'll also leave the link here in case you'd like to add something: https://docs.google.com/document/d/1VMyUdnJr26z6iPHD06LicrlwHplPpYARQ20CVYoLOIM/edit?usp=sharing

Thank you for your time and attention, I really appreciate it :)

**Comment by kgodey** [comment]
Thanks @apdsrocha! :)

**Comment by corinthc** [comment]
Greetings everyone.😊
Just want to share a mock license workflow for **Unsplash**
[License integration process.pdf](https://github.com/creativecommons/mp/files/3800012/License.integration.process.pdf)
Unsplash Mockup with License chooser - https://drive.google.com/open?id=1SmvBryVVIWSDNF4nbnj0xmM_NGxH1y-u
Unsplash Mockup with default license - https://drive.google.com/open?id=1QVLpGj7-gs4IXAnTDKTRLDs30btheONK

**Comment by kgodey** [comment]
Thank you @corinthc!

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this issue.
