### ISSUE TITLE
Redesign an existing CC license workflow

### ISSUE THREAD

**Issue by kgodey** [creativecommons/mp#57]
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Take an existing platform’s implementation of the CC licensing workflow and create a mockup of a redesign that is more user friendly.

**Comment by NicoleOliv** [comment]
i'd like if you clarify this task. Why a mockup? isn't a mockup a preview of a product? doesn't make more sense to do something like a infographic? and i have another question: a licensing workflow means that i should demonstrate the process that it takes to have a CC licensing? is that it or i got it wrong? and existing platform implementation of the CC licensing is platforms like youtube, vimeo? i'm very excited to get starting those design tasks, but i'm quite confused

**Comment by kgodey** [comment]
Clarification on what "CC licensing workflow" means: On platforms like YouTube and Medium, once you create content, you can share it under a license, we're describing the UI that the platform uses to enable that as the "CC licensing workflow". e.g. see screenshots of the Medium workflow in this blog post: https://blog.medium.com/explicit-post-licensing-3aa1df783f8d

**Comment by kgodey** [comment]
@NicoleOliv The platform toolkit project involves demonstrating to platforms how they should implement CC licensing on their platforms. A mockup of the UI they should use would be a great tool to use in this demonstration so that's why we suggest it. An infographic would also be helpful, if you want to do that instead, go ahead.

Taking a step back, the task for the platform toolkit is to create a guide for platforms to implement CC licensing. e.g. if you are starting a new blogging site or a video upload site and you want to be able to allow your users to license their blog posts or videos under CC licenses, you would use this guide to figure out how to implement the UI for showing the license options, etc. I hope that helps.

**Comment by corinthc** [comment]
Greetings everyone. 
Thank you for the clarification @kgodey, I was also very lost.
This is what I came up with, to the best of my understanding.
Please take a look at it and let me know if I understood correctly😊.

**Files**
[Mockup Description.pdf](https://github.com/creativecommons/mp/files/3722602/Mockup.Description.pdf)
[Wireframe.pdf](https://github.com/creativecommons/mp/files/3722603/Wireframe.pdf)
[Mockup.pdf](https://github.com/creativecommons/mp/files/3722604/Mockup.pdf)
[Mockup-Animated](https://user-images.githubusercontent.com/45762240/66724512-981d5700-ee1e-11e9-8568-cd4061c08274.gif)
https://drive.google.com/open?id=1aetTgdyxx5hZrIHxAVP_bwysA8Xk5L1Z (a video of the animated mockup)

**Comment by kgodey** [comment]
@corinthc this is great work! I'm sure it will be useful for you for your final application :)

**Comment by corinthc** [comment]
Thank you

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this issue.
