### ISSUE TITLE
Revise a page on the CC public wiki

### ISSUE THREAD

**Issue by kgodey** [creativecommons/mp#58]
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
The [Creative Commons Wiki](https://wiki.creativecommons.org/) has a lot of old/inaccurate content. Revise one wiki page and post a link to your contribution here. Please ask questions about any content you are unsure of.

To get edit access to the wiki, please sign up for a [CCID here](https://login.creativecommons.org/register.php) and tell us about it in `#cc-gsoc-outreachy` on Slack. We will give your account edit permissions.

**Comment by mchesler613** [comment]
Can you please give me some hints on which areas require updating?  Thanks. I'm from Outreachy.

**Comment by mchesler613** [comment]
@kgodey I would like to update this page, https://opensource.creativecommons.org/community/ to include the tag, #cc-gsoc-outreachy as I was led to this page but I couldn't navigate to find the outreachy channel on slack.  Is this something amenable to you?  I have signed up for a CCID, but I don't think my ID gives me sufficient permission to edit this page. Thanks.

**Comment by discombobulateme** [comment]
Hi @mchesler613 I have the same doubt as you, did you find a parameter to compare and update the pages? Thank you :)

**Comment by mchesler613** [comment]
Yes @discombobulateme   The FAQ page to compare with is here https://creativecommons.org/faq/

**Comment by discombobulateme** [comment]
Thank you :) that was really nice @mchesler613

**Comment by discombobulateme** [comment]
@mchesler613 I am a bit lost, but think we should ask for permission not here but on slack. Here says is on #cc-gsoc-outreachy but I think it's on #cc-outreachy-platform-toolkit ... just in case I posted on both. Mentors may be SUPER busy though, if I found out something I post it here for you as well :)

**Comment by mchesler613** [comment]
@discombobulateme Yes, this thread is for the Platform Toolkit and it's confusing to have this FAQ-related post here.  The WIKI FAQ thread is https://github.com/creativecommons/faq.  Thank you for sharing with me the same confusion.

**Comment by discombobulateme** [comment]
@mchesler613 did you get the authorisation? Mentors are available on Slack at #cc-gsoc-outreachy :)

**Comment by mchesler613** [comment]
@discombobulateme Yes, I got the authorization from the Slack channel.

**Comment by discombobulateme** [comment]
Hey all :) just made several changes on [Developers](https://wiki.creativecommons.org/wiki/Developers) based on [Join the CC Developer Community](https://opensource.creativecommons.org/community/), [Contributing Code](https://opensource.creativecommons.org/contributing-code/) and [Open Source at CC](https://opensource.creativecommons.org/). I tried to respect the previous scheme but updating information and content (to what I understand is focused on Developers who wants to contribute). Please let me know if this type of update is what is expected or if I supposed to go into other direction :) . After feedback I can happily contribute more :)

**Comment by kgodey** [comment]
@discombobulateme nice work! I'd recommend updating the page to remove any duplicate information so that if anything on opensource.creativecommons.org changes, we don't also have to update the wiki. It's okay if the Developers wiki page is very short :)

**Comment by discombobulateme** [comment]
Thanks @kgodey :) just a last question about it to move on, is it important to mention technologies being used? In the older page there were the mention, but it's really unupdated (got a screen shot to compare) 
<img width="1043" alt="Screen Shot 2019-10-03 at 22 01 44" src="https://user-images.githubusercontent.com/7980624/66192421-b5b92680-e690-11e9-8e6e-589608e04c76.png">

**Comment by kgodey** [comment]
No, you can delete the technologies being used section.

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this issue.
