### ISSUE TITLE
Text on buttons overflows

### ISSUE THREAD

**Issue by palak199** [creativecommons/mp#72]
## Description

The text on the buttons overflows on mobile view. I have added screen shots for the same.

## Screenshots

![ss2](https://user-images.githubusercontent.com/43077980/90955411-e2d61980-e49a-11ea-8594-cadb3ecb2ab6.png)
![ss1](https://user-images.githubusercontent.com/43077980/90955414-e36eb000-e49a-11ea-9192-399acba9b9b7.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by kgodey** [comment]
Thanks for reporting this, @palak199, feel free to send a PR.

**Comment by prsndp** [comment]
I want to contribute to this issue?? pls assign me

**Comment by Soundug** [comment]
Hello! If this issue is still open, I would like to work on this one.
Please let me know.

**Comment by CapriciousRebel** [comment]
Hello, Is this issue still open? I would like to work on this one.

**Comment by ImaJin14** [comment]
Hi @TimidRobot, if this issue is still open and valid I'll like to work on it...

**Comment by JeffyDave** [comment]
Hi, Please I would love to work on this issue, can it be assigned to me?

**Comment by Ramireddyvatte** [comment]
Hello, Is this issue still open? I would like to work on this one.
