### ISSUE TITLE
Text Overflow in Divs

### ISSUE THREAD

**Issue by shubhanshu02** [creativecommons/mp#76]
## Description
Text overflows in boxes under the "WHAT COMES AFTER IMPLEMENTATION" and "ABOUT" heading when viewed on devices with a width between 768px to around 1300px.

## Reproduction
1. Open this [link](https://creativecommons.org/platform/toolkit/).
2. Open the Developer Tools
3. Change the screen width accordingly
4. See the overflow.

## Expectation
There should not be any overflow in these cases too.

## Screenshots
![Screenshot from 2021-01-22 22-52-39](https://user-images.githubusercontent.com/54344426/105523768-d3d2ec00-5d04-11eb-9db5-3d2ad270e2e4.png)
![Screenshot from 2021-01-22 22-52-52](https://user-images.githubusercontent.com/54344426/105523777-d59caf80-5d04-11eb-9532-fab484e35aaa.png)

## Environment
 - Device: laptop
 - OS: Ubuntu 20.04
 - Browser: Chrome, Firefox
 - Version: 88.0.4324

## Resolution
- [ ] I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
## Tips for fixing:

In lieu of changing `word-wrap` like one might think initially, I would recommend looking at removing or changing some hardcoded widths and heights from these cards as seen in the below screenshots:

<img width="771" alt="2021-01-25-123" src="https://user-images.githubusercontent.com/6351754/105754481-36d3a700-5eee-11eb-8df7-48e6eca21144.png">

<img width="771" alt="2021-01-25-122" src="https://user-images.githubusercontent.com/6351754/105754472-31765c80-5eee-11eb-8592-38d15cc461ae.png">

**Comment by cyberShaw** [comment]
Is this issue open for working on? I'm new and interested in Open Source and I'd love to contribute :D

**Comment by zackkrida** [comment]
@cyberShaw sure thing! You can work on this.

**Comment by abhipaiangle** [comment]
Is the issue fixed? I wanted to start working on it

**Comment by zackkrida** [comment]
@abhipaiangle you're welcome to work on it as well, while we await any feedback from @cyberShaw 😄

**Comment by Soundug** [comment]
Is this issue still open? I would like to work on this one. Please let me know.

**Comment by amruta-kashikar** [comment]
Is this issue open? I am new to open source and would like to contribute to this organization.

**Comment by renuka142** [comment]
hello @zackkrida , can I work on this issue as I am new to open source and this community!!

**Comment by CapriciousRebel** [comment]
Hello, Is this issue still open? I would like to work on this one.

**Comment by zackkrida** [comment]
Hi @CapriciousRebel you're welcome to work on this. Thank you

**Comment by zackkrida** [comment]
Hi @CapriciousRebel this issue is closed, but there's a similar issue #72 you could look at. Thank you!
